---
title: "lab2_fifa_sophie"
output: pdf_document
date: '2022-04-01'
---

```{r message=FALSE}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(patchwork)
library(sandwich)
library(lmtest)
library(fec16)
library(stargazer)
library(nnet)
library(corrplot)
library(car)
library(GGally)

```

```{r}
df <- read.csv('data/interim/fifa22_interim_sophie.csv')
df <- na.omit(df)
dim(df) #1358   24

```



```{r}
# key variables only
# start with polynomial assumption
model1 <- lm(log(Value) ~ Age + I(Age^2)+
                         Height + Weight + Special,
             data=df)

# model with I(Age) has high VIF. Removing I(Age)
model2 <- lm(log(Value) ~ Age +
               I(Age^2) + 
               Height + Weight + Special + Contract.Years +
               International.Reputation,
              data=df)

# Another potentially significant coefficient is Contract Years and Special
model3 <- lm(log(Value) ~ Age +
              I(Age^2) +
             Height + Weight+
               International.Reputation+
               Contract.Years +
               Agility +
               Strength+
               Jumping+
              Acceleration+
               Stamina+
               Weak.Foot,
          data=df)

stargazer(model1, model2, model3, type="text", no.space = TRUE)
```




```{r}

print("Model(1) VIF")
vif(model1)
print("Model(2) VIF")
vif(model2)
print("Model(3) VIF")
vif(model3)


model_msr <- c()
model_msr["model1 msr"] <- mean(resid(model1)^2)
model_msr["model2 msr"] <- mean(resid(model2)^2)
model_msr["model3 msr"] <- mean(resid(model3)^2)
print(model_msr)



```

```{r}

for (i in (1:6)){
  plot(model1, which=i)
  plot(model2, which=i)
  plot(model3, which=i)

}


anova(model1, model2, model3, test="F")

anova(model1, model2, test="F")


anova(model2, model3, test="F")


coeftest(model2, vcovHC)

```

